### PR TITLE
add support for visual-regexp

### PR DESCRIPTION
**Pull request by NeoISE**
I'm conflicted for `vr/group-*` faces between a red-orange-yellow color trio or using the current setup of blue-indigo-purple trio. I like the "bluer" scheme more, but I can change it if you don't like it.

### CODE REVIEW

**Comment by waymondo** [comment]
Can you supply a couple screenshots that represent how this looks? The current convention is to use `yellow-1` for temporary string-matching highlighting, so it might be best to have the most primitive matching face be yellow and modify the styles from there.

**Comment by NeoISE** [comment]
The overall string highlighting of visual-regexp is done by alternating the background color between matches so I used the regular and its `-1` variant for those; I just used the color teal since it was the closest to the original color.

The regexp grouping from the regexp matching is done by alternating the 3 `vr/group` colors. So I used the current colors to be as close to the real color to not be too high in contrast.

I can post some screenshots in a little while.

**Comment by NeoISE** [comment]
apropospriate-theme-normal
Without colors.

apropospriate-theme-visual-regexp under "blue" scheme
This is the theme with "blue-ish" scheme.

apropospriate-theme-visual-regexp under "red" scheme
This is the theme with "red-ish" scheme.

I'm starting to feel that it would be better to not highlight with color but instead use the colors as foreground instead and just inherit from `highlight` face.

**Comment by waymondo** [comment]
Yeah I agree about making the colors foreground colors instead and doing a very subtle color for the background, maybe `light-emphasis-2`? It's hard to read through the contrast as is. I prefer the red-ish theme for consistency too.

**Comment by NeoISE** [comment]
I updated the faces.

Here is the light theme:
image

Here is the dark theme:
image

**Comment by waymondo** [comment]
Cool, looks good. Thanks!

**Pull request merged**
